version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: inventory_postgres
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/install_invoice_system.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: >
      postgres 
      -c max_connections=50
      -c shared_buffers=128MB
      -c effective_cache_size=512MB
      -c work_mem=4MB

  # FastAPI Backend
  backend:
    build: .
    container_name: inventory_backend
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/inventory_db
      - PYTHONPATH=/app/backend
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./sample_invoices:/app/sample_invoices
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # React Frontend (Development)
  frontend:
    image: node:18-alpine
    container_name: inventory_frontend
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3001"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  postgres_data:
  node_modules:
