version: '3.8'

services:
  # Complete System Setup with Database
  postgres:
    image: postgres:15-alpine
    container_name: inventory_postgres
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/install_invoice_system.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend with automatic dependency installation
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.auto
    container_name: inventory_backend
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/inventory_db
      - PYTHONPATH=/app/backend
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./sample_invoices:/app/sample_invoices
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend with automatic setup
  frontend:
    image: node:18-alpine
    container_name: inventory_frontend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
